version: '2'
services:
  nofuss:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    ports:
      - "8267:8267"
    restart: always
    environment:
      NODE_ENV: production
      PORT: 8267
